// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtzYD1vjmGR2S_JplKtiirjo5ksK0B_Lc',
    appId: '1:906552271889:web:99710155965efd74a17db0',
    messagingSenderId: '906552271889',
    projectId: 'conectasaudepi',
    authDomain: 'conectasaudepi.firebaseapp.com',
    storageBucket: 'conectasaudepi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTiZHvVJIYTO9jNbRcI-_Wrn2qrrxO7hk',
    appId: '1:906552271889:android:8f14b5667e57a39ea17db0',
    messagingSenderId: '906552271889',
    projectId: 'conectasaudepi',
    storageBucket: 'conectasaudepi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAowaBylf-cljerYNS3oWlw3HXpRHMJZ0M',
    appId: '1:906552271889:ios:18007f8c0ec45daea17db0',
    messagingSenderId: '906552271889',
    projectId: 'conectasaudepi',
    storageBucket: 'conectasaudepi.firebasestorage.app',
    iosBundleId: 'com.conectasaudepi.conectasaude',
  );
}
